# Generated by Django 5.2.4 on 2025-07-07 09:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('objectives', models.TextField(help_text='Provide a general overview of objectives. Specific objectives can be broken down if needed.')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='ClubEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Unique URL identifier (e.g., 'indabax').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='communities/')),
                ('website_url', models.URLField(blank=True, help_text="URL to the community's section/app (e.g., /communities/indabax/).", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which communities are displayed.')),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutivePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which positions are displayed.')),
            ],
            options={
                'verbose_name': 'Executive Position',
                'verbose_name_plural': 'Executive Positions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='A unique slug for the URL, auto-generated if left blank.', max_length=255, unique=True)),
                ('author', models.CharField(blank=True, help_text='Name of the author or posting entity.', max_length=100)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'News Post',
                'verbose_name_plural': 'News Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(help_text='Upload partner logo (recommended size: 150x150 pixels)', upload_to='partners/')),
                ('website_url', models.URLField(blank=True, help_text="Link to the partner's website.", null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which partners are displayed.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(help_text='A unique identifier for the URL, auto-generated if left blank.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Resource Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Kabale University AI Club', max_length=200)),
                ('main_tagline', models.CharField(blank=True, help_text='A catchy tagline for the homepage hero section.', max_length=255)),
                ('featured_announcement', models.TextField(blank=True, help_text='A short announcement to display prominently on the homepage.')),
                ('homepage_background_image', models.ImageField(blank=True, null=True, upload_to='site_config/backgrounds/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='ClubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, help_text='e.g., 10:00 AM - 12:00 PM', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='club_events/')),
                ('is_upcoming', models.BooleanField(default=True, help_text='Uncheck for past events manually or update automatically.')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuai_club.clubeventtype')),
            ],
            options={
                'verbose_name': 'Club Event',
                'verbose_name_plural': 'Club Events',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='kuai_club_leaders/')),
                ('bio', models.TextField(blank=True)),
                ('term_start', models.DateField(default=datetime.date.today)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuai_club.executiveposition')),
            ],
            options={
                'verbose_name': 'Executive Board Member',
                'verbose_name_plural': 'Executive Board Members',
                'ordering': ['position__order', '-term_start', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Planned', 'Planned')], default='Ongoing', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='club_projects/')),
                ('is_featured', models.BooleanField(default=False, help_text='Check to feature this project on the homepage or dedicated section.')),
                ('research_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuai_club.researcharea')),
            ],
            options={
                'verbose_name': 'Club Project',
                'verbose_name_plural': 'Club Projects',
                'ordering': ['status', '-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuai_club.resourcecategory')),
            ],
            options={
                'verbose_name_plural': 'Resource Links',
                'ordering': ['category__order', 'title'],
            },
        ),
    ]
