# Generated by Django 5.2.2 on 2025-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for the site. Recommended size: 1920x1080px', null=True, upload_to='backgrounds/'),
        ),
    ]
