# Generated by Django 5.2.2 on 2025-07-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='who_we_are_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='who_we_are_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='who_we_are_title',
            field=models.CharField(default='Who We Are', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='why_exist_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='why_exist_title',
            field=models.CharField(default='Why We Exist', max_length=100),
        ),
    ]
