# Generated by Django 5.2.4 on 2025-07-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, help_text="Unique URL identifier (e.g., 'indabax').", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique slug for the URL, auto-generated if left blank.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='slug',
            field=models.SlugField(blank=True, help_text='A unique identifier for the URL, auto-generated if left blank.', max_length=100, unique=True),
        ),
    ]
