# Generated by Django 5.2.2 on 2025-08-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0002_sitesettings_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='column_position',
        ),
    ]
