# Generated by Django 5.2.4 on 2025-07-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0002_alter_community_slug_alter_newspost_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcharea',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which research areas are displayed.'),
        ),
    ]
