# Generated by Django 5.2.4 on 2025-07-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0003_researcharea_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Partners'},
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='website_url',
            new_name='website_link',
        ),
        migrations.AddField(
            model_name='partner',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first on the page.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('sponsor', 'Sponsor'), ('collaborator', 'Collaborator'), ('academic', 'Academic Partner'), ('other', 'Other')], default='collaborator', max_length=50),
        ),
    ]
