# Generated by Django 5.2.2 on 2025-08-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0003_remove_aboutus_column_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.TextField(blank=True, help_text='External collaborators or partner organizations', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.CharField(blank=True, help_text='Main project leader or coordinator', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_sponsor',
            field=models.CharField(blank=True, help_text='Project sponsor or funding organization', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.TextField(blank=True, help_text='List team members (one per line or comma-separated)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_people_involved',
            field=models.PositiveIntegerField(default=0, help_text='Total number of people involved in this project'),
        ),
    ]
