# Generated by Django 5.2.4 on 2025-07-09 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0004_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcecategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Resource Categories'},
        ),
        migrations.AlterModelOptions(
            name='resourcelink',
            options={'ordering': ['category__display_order', 'display_order', 'title']},
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='order',
        ),
        migrations.AlterUniqueTogether(
            name='resourcelink',
            unique_together={('category', 'title')},
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='resourcelink',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first within their category.'),
        ),
        migrations.AddField(
            model_name='resourcelink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='kuai_club.resourcecategory'),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='resourcelink',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='resourcelink',
            name='is_featured',
        ),
    ]
