# Generated by Django 5.2.2 on 2025-07-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0002_aboutus_who_we_are_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project or Initiative title', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short summary of the project')),
                ('description', models.TextField(help_text='Full details or body content')),
                ('contact_email', models.EmailField(blank=True, help_text='Email to reach out about this project', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number if applicable', max_length=20, null=True)),
                ('url', models.URLField(blank=True, help_text='External or internal project link', null=True)),
                ('image', models.ImageField(blank=True, help_text='Project image or banner', null=True, upload_to='project_images/')),
                ('is_published', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        # migrations.DeleteModel(
        #     name='ContactUs',
        # ),
    ]
