# Generated by Django 5.2.2 on 2025-07-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0012_project_delete_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='column_position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=5),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='objectives',
            field=models.TextField(help_text='Provide a general overview of objectives.'),
        ),
    ]
