# Generated by Django 5.2.2 on 2025-07-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0013_alter_aboutus_column_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
