# Generated by Django 5.2.2 on 2025-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0014_aboutus_mission_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
