# Generated by Django 5.2.2 on 2025-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0016_alter_event_options_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='events_section_bg/'),
        ),
    ]
