# Generated by Django 5.2.2 on 2025-07-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0017_event_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='end_date',
            field=models.DateField(blank=True, help_text='End of leadership period (auto-calculates 6 months if left empty)', null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='start_date',
            field=models.DateField(default=('2025-07-15'), help_text='Start of leadership period'),
            preserve_default=False,
        ),
    ]
