# Generated by Django 5.2.2 on 2025-07-15 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0018_leader_end_date_leader_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Start of leadership period'),
        ),
    ]
