# Generated by Django 5.2.2 on 2025-07-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0019_alter_leader_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background slider image for this news', null=True, upload_to='news_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Main image for the news card', null=True, upload_to='news_images/'),
        ),
    ]
