# Generated by Django 5.2.2 on 2025-07-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuai_club', '0020_news_background_image_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_date', '-id'],
            },
        ),
    ]
