# Generated by Django 5.2.4 on 2025-07-07 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slider/')),
                ('description', models.TextField(blank=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Technical Lead', 'Technical Lead'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Graphics Designer Lead', 'Graphics Designer Lead'), ('Social Media Manager', 'Social Media Manager'), ('Event Manger', 'Event Manager'), ('Mobilizer', 'Mobilizer'), ('Year One Representative', 'Year One Representative'), ('Year Two Representative', 'Year Two Representative'), ('Presidential Advisor', 'Presidential Advisor')], max_length=50)),
                ('photo', models.ImageField(upload_to='leaders/')),
                ('term_start', models.DateField()),
                ('term_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indabax_app.tutorialcategory')),
            ],
        ),
    ]
