# Generated by Django 5.2.4 on 2025-07-22 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(default='About IndabaX Kabale AI Club', max_length=200)),
                ('main_paragraph', models.TextField()),
                ('purpose_heading', models.CharField(default='Our Purpose and Objectives', max_length=200)),
                ('purpose_paragraph', models.TextField()),
                ('affiliations_heading', models.CharField(blank=True, default='Affiliations and Contact', max_length=200, null=True)),
                ('affiliations_paragraph', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='AffiliationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('about_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_links', to='indabax_app.aboutcontent')),
            ],
            options={
                'verbose_name': 'Affiliation Link',
                'verbose_name_plural': 'Affiliation Links',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('about_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='indabax_app.aboutcontent')),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
    ]
