# Generated by Django 5.2.4 on 2025-07-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0002_aboutcontent_affiliationlink_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, help_text='e.g., 9:00 AM - 12:00 PM', max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_url', models.URLField(blank=True, help_text='Google Form URL or similar registration link', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_upcoming', models.BooleanField(default=True, help_text='Check if this is an upcoming event.')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(default='Welcome to IndabaX Kabale AI Club!', max_length=200)),
                ('main_subheading', models.TextField(default='Your premier hub for Artificial Intelligence education, research, and community engagement in Kabale, Uganda.')),
                ('about_home_heading', models.CharField(default='About Our Initiative', max_length=200)),
                ('about_home_paragraph', models.TextField(default='IndabaX Kabale is part of the larger Deep Learning IndabaX movement, aimed at strengthening African Machine Learning. We foster a vibrant community, providing resources and opportunities for learning, collaboration, and innovation in AI.')),
                ('about_home_image', models.ImageField(blank=True, help_text="Image for the 'About Our Initiative' section on homepage.", null=True, upload_to='home_content/')),
                ('cta_heading', models.CharField(default='Get Involved!', max_length=200)),
                ('cta_paragraph', models.TextField(default='Ready to dive into the world of AI? Join our upcoming events and connect with us.')),
                ('cta_primary_button_text', models.CharField(default='Upcoming Events', max_length=50)),
                ('cta_primary_button_url', models.URLField(blank=True, help_text='URL for the primary Call to Action button (e.g., Upcoming Events page).', null=True)),
                ('cta_secondary_button_text', models.CharField(default='Contact Us', max_length=50)),
                ('cta_secondary_button_url', models.URLField(blank=True, help_text='URL for the secondary Call to Action button (e.g., Contact page).', null=True)),
            ],
            options={
                'verbose_name_plural': 'Home Page General Content',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which partners are displayed.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fas fa-graduation-cap)', max_length=50)),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which pillars are displayed.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
