# Generated by Django 5.2.4 on 2025-07-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0003_event_homepagecontent_partner_pillar'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image for the main hero slider.', upload_to='gallery_hero_images/')),
                ('title', models.CharField(blank=True, help_text='Short title for the hero image (optional).', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description for the hero image (optional).')),
                ('order', models.IntegerField(default=0, help_text='Order in which images appear in the slider.')),
            ],
            options={
                'verbose_name': 'Hero Gallery Image',
                'verbose_name_plural': 'Hero Gallery Images',
                'ordering': ['order'],
            },
        ),
    ]
