# Generated by Django 5.2.4 on 2025-07-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0004_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for the rotating hero background.', upload_to='hero_backgrounds/')),
                ('title', models.CharField(blank=True, help_text='Internal title for admin reference.', max_length=200, null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which images should appear in the rotation.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active images will be used in the rotation.')),
            ],
            options={
                'verbose_name': 'Hero Background Image',
                'verbose_name_plural': 'Hero Background Images',
                'ordering': ['order'],
            },
        ),
    ]
