# Generated by Django 5.2.4 on 2025-07-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0005_herobackgroundimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'ordering': ['-is_current', 'position']},
        ),
        migrations.AddField(
            model_name='leader',
            name='bio',
            field=models.TextField(blank=True, help_text='A brief statement or fun fact about the leader.'),
        ),
        migrations.AddField(
            model_name='leader',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Check this box if the person is a current leader. Uncheck it for past leaders.'),
        ),
        migrations.AddField(
            model_name='leader',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
