# Generated by Django 5.2.4 on 2025-07-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0006_alter_leader_options_leader_bio_leader_github_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='term_end',
        ),
    ]
