# Generated by Django 5.2.4 on 2025-07-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0007_remove_leader_term_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('embed_code', models.TextField(help_text='Paste the full embed code from Google Photos here.')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
