# Generated by Django 5.2.4 on 2025-07-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0008_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='embed_code',
        ),
        migrations.AddField(
            model_name='album',
            name='link',
            field=models.URLField(default='https://photos.google.com/albums/', help_text='Paste the shareable link from Google Photos here.', max_length=400),
            preserve_default=False,
        ),
    ]
