# Generated by Django 5.2.4 on 2025-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0010_session_sessionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='guest_speakers_info',
            field=models.TextField(blank=True, help_text='Enter names of guest speakers not listed above, or additional speaker details. Use new lines for each speaker.', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='speakers',
            field=models.ManyToManyField(blank=True, help_text='Select existing leaders who spoke at this session.', related_name='sessions_spoken_at', to='indabax_app.leader'),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='tagline',
            field=models.CharField(blank=True, help_text="A short, catchy phrase for the session (e.g., 'Discover Hidden Patterns').", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='venue',
            field=models.CharField(blank=True, help_text="e.g., 'New Computer Lab', 'Online via Zoom'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, help_text='Provide a general overview and detailed description of the session content.', null=True),
        ),
    ]
