# Generated by Django 5.2.4 on 2025-07-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0011_session_end_time_session_guest_speakers_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillar',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='pillar',
            name='button_url',
        ),
    ]
