# Generated by Django 5.2.4 on 2025-07-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabax_app', '0012_remove_pillar_button_text_remove_pillar_button_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('physical_address', models.CharField(blank=True, max_length=255, verbose_name='Physical Address')),
                ('footer_description', models.TextField(blank=True, help_text='A short description for the footer.', verbose_name='Footer Club Description')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
